spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/workflow_db}

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
    task:
      scheduling:
        pool:
          size: 2
      execution:
        pool:
          core-size: 4
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

jwt:
  secret: c3VwZXJzZWNyZXRrZXlmb3Jqd3R0b2tlbmF1dGhlbnRpY2F0aW9uMjAyNA==
  expiration: 86400000
app: 
  file:
    upload-dir: ./uploads
    storage: local
    
logging:
  level:
    com.workflow.bpm: DEBUG
    org.springframework.security: DEBUG